### ISSUE TITLE
My Wishlist is not showing any items

### ISSUE THREAD

**Issue by OahidZihad** [RifatShovon/KinteChai#4]
After using Glide for product image in WishlistAdapter.java file. Then My Wishlist not showing any items.

**Comment by Zishan-Ali171** [comment]
it is happen most probably holdding two fragments in same time and because of this ,it can not switching the other fragment. 
Though not sure :p

**Comment by OahidZihad** [comment]
it was a silly mistake made by me. Actually after using Glide for product image in WishlistAdapter.java file, the whole whishlist fragment connected with Firebase. And in the firebase I didn't make any type of products. That's why it shows nothing. 

Sorry for the inconvenience.
